

import Common.OpenPdf;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jema.ConnectionProvider;
import jema.MethodistUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CODE
 */
public class AddResults extends javax.swing.JFrame {

    /**
     * Creates new form AddResults
     */
    public AddResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlevel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCscore = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEscore = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPLOAD RESULTS HERE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 1218, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 120, -1, -1));

        txtSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 117, 300, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 170, -1, -1));
        getContentPane().add(txtlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 167, 300, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Term");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 225, -1, -1));
        getContentPane().add(txtTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 222, 300, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 120, -1, -1));
        getContentPane().add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 117, 300, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CLass Score");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));
        getContentPane().add(txtCscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 167, 300, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Exam Score");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 225, -1, -1));
        getContentPane().add(txtEscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 222, 300, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL Score");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 271, -1, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 268, 300, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 365, -1, -1));

        resultsTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Class Score", "Exams Score", "Total Score", "Position"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 442, 885, 221));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 271, -1, -1));
        getContentPane().add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 268, 300, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminDashboardBackground.png"))); // NOI18N
        jLabel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel10ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jLabel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel10ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
        try{
            Connection Con = ConnectionProvider.getCon();
            Statement st = Con.createStatement();
            ResultSet rs = st.executeQuery("Select *from results");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("subject"),rs.getString("classScore"),rs.getString("examScore"),rs.getString("total"),rs.getString("position")});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       txtTotal.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
String name = txtSname.getText();
String level = txtlevel.getText();
String term = txtTerm.getText();
String position = txtPosition.getText();
String subject = txtSubject.getText();
String classScore = txtCscore.getText();
String exams = txtEscore.getText();
txtTotal.setEditable(false);

if (name.equals("")) {
    JOptionPane.showMessageDialog(null, "Student Name field is required");
} else if (level.equals("")) {
    JOptionPane.showMessageDialog(null, "Class field is required");
} else if (term.equals("")) {
    JOptionPane.showMessageDialog(null, "Term field is required");
} else if (position.equals("")) {
    JOptionPane.showMessageDialog(null, "Position field is required");
} else if (subject.equals("")) {
    JOptionPane.showMessageDialog(null, "Subject field is required");
} else if (classScore.equals("")) {
    JOptionPane.showMessageDialog(null, "Class score field is required");
} else if (exams.equals("")) {
    JOptionPane.showMessageDialog(null, "Exam field is required");
} else {
    try {
        int classScoreInt = Integer.parseInt(classScore);
        int examsInt = Integer.parseInt(exams);
        int total = classScoreInt + examsInt;
        txtTotal.setText(String.valueOf(total));

        Connection con = ConnectionProvider.getCon();
        PreparedStatement ps = con.prepareStatement("INSERT INTO results(studentName, class, term, position, subject, classScore, examScore, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
        ps.setString(1, name);
        ps.setString(2, level);
        ps.setString(3, term);
        ps.setString(4, position);
        ps.setString(5, subject);
        ps.setInt(6, classScoreInt);
        ps.setInt(7, examsInt);
        ps.setInt(8, total);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Results added successfully");
        setVisible(false);
        new AddResults().setVisible(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers for class score and exam score");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextField txtCscore;
    private javax.swing.JTextField txtEscore;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTerm;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtlevel;
    // End of variables declaration//GEN-END:variables
}
