
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import jema.ConnectionProvider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CODE
 */
public class AddStudents extends javax.swing.JFrame {
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
     public String mobileNumberPattern = "^[0-9]*$";


    /**
     * Creates new form AddStudents
     */
    public AddStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtStudentName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateDOB = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtclass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfather = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmother = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("ADD STUDENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 13, -1, -1));

        jLabel2.setText(" Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 93, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 850, 10));
        getContentPane().add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 127, 300, -1));

        jLabel3.setText("Date Of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 177, -1, -1));
        getContentPane().add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 200, 300, -1));

        jLabel4.setText("class");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 248, -1, -1));
        getContentPane().add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 282, 300, -1));

        jLabel5.setText("Name of Father");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 93, -1, -1));
        getContentPane().add(txtfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 127, 300, -1));

        jLabel6.setText("Name of Mother");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 177, -1, -1));
        getContentPane().add(txtmother, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 200, 300, -1));

        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 248, -1, -1));
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 282, 300, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 332, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 13, 36, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        String StudentName = txtStudentName.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-mm-yyy");
        Date date = dateDOB.getDate();
        String dob = "";
        if (date != null) {
            dob = dFormat.format(dateDOB.getDate());
        }
        String Mobilenumber = txtnumber.getText();
        String level = txtclass.getText();
        String father = txtfather.getText();
        String mother = txtmother.getText();
        if (StudentName.equals("")) {
            JOptionPane.showMessageDialog(null, " Student Name filled is required");
        } else if (dob.equals("")) {
            JOptionPane.showMessageDialog(null, "DOB filled is required");
        } else if (Mobilenumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile number is  filled is required");
        } else if (!Mobilenumber.matches(mobileNumberPattern) || Mobilenumber.length() != 10) {
            JOptionPane.showMessageDialog(null, "Mobile Number filled is invalid");
        } else if (father.equals("")) {
            JOptionPane.showMessageDialog(null, "Father Name  filled is required");
        } else if (mother.equals("")) {
            JOptionPane.showMessageDialog(null, "Mother Name filled is required ");
        } 
         else if (level.equals("")) {
            JOptionPane.showMessageDialog(null, "class filled is required");
        } else {
            try {
                Connection Con = ConnectionProvider.getCon();
                PreparedStatement ps = Con.prepareStatement("Insert Into students(studentName, fatherName,DOB,mobileNumber,motherName,class) values(?,?,?,?,?,?)");
                ps.setString(1,StudentName);
                ps.setString(2,father);
                ps.setString(3,dob);
                ps.setString(4,Mobilenumber);
                ps.setString(5,mother);
                ps.setString(6,level);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Student added successfuly");
                setVisible(false);
                new AddStudents().setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtfather;
    private javax.swing.JTextField txtmother;
    private javax.swing.JTextField txtnumber;
    // End of variables declaration//GEN-END:variables
}
